#include <bits/stdc++.h>
using namespace std;

int main()
{
	freopen("Z:/my2.txt", "r", stdin);		//	comment this line to give input from console
	
	cout << "Enter the productions and give the space between left and right side (give - to exit) : \n";
	
	map<string, string> mp;
	char T;
	string str;
	
	while(true)
	{
		cin >> T;
		if(T == '-')		break;
		cin >> str;
		if(mp.count(str))
			mp[str] += T;
		else
			mp[str] = T;	
	}
	
//	for (map<string, string> :: iterator p = mp.begin(); p != mp.end(); p++)
//		cout << p->first << "  :  " << p->second << endl;
	
	cout << "\n Now give the input and starting terminal \n";
	
	string input;
	char start;
	cin >> input >> start;
	
	int l = input.length();
	string mat[l][l];
	
	for (int i = 0; i < l; i++)	
		for (int j = 0; j < l; j++)
			mat[i][j] = "";
	
	for (int j = 0; j < l; j++)
	{
		string temp = "";
		temp += input[j];
		mat[0][j] = mp[temp];
	}
	
	for (int i = 2; i <= l; i++)
	{
		for(int j = 0; j <= l - i; j++)
		{
			for(int k = 1; k < i; k++)
			{
				if(mat[k - 1][j].length() && mat[i - k - 1][j + k].length())
				{
					for (int l = 0; l < mat[k - 1][j].length(); l++)
					{
						for (int m = 0; m < mat[i - k - 1][j + k].length(); m++)
						{
							str = mat[k - 1][j][l];		
							str += mat[i - k - 1][j + k][m];
//							cout << i << "  " << j << "  " << str << endl;

							if(mp.count(str))
							{
								string temp = mp[str];
								for (int n = 0; n < temp.length(); n++)
								{
									if(mat[i - 1][j].find(temp[n]) == string::npos)
										mat[i-1][j] += temp[n];		
								}						
							}
						}
					}
				}
							
			}
		}
	}
	
	for (int i = l - 1; i >= 0; i--)
	{
		for (int j = 0; j < l; j++)
			cout << mat[i][j] << "   ";
		cout << endl;
	}
	
	if(mat[l - 1][0].find(start) != string::npos)
		cout << "input can be generated by given CFG\n";
	else
		cout << "input can't be generated by given CFG\n";
}

/*
Sample Input 1 : 

S AB
S BC
A BB
A 0
B BA
B 1
C BC
C AA
C 0
-
110100 S

Sample Input 2:

S AB
S BC
A BA
A a
B CC
B b
C AB
C a
-
baaba S
*/
