/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arraysum.h"


void
arraysum_calc_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	args  arraysum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARRAYSUM_CALC, ARRAYSUM_CALC_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	struct args arg;
	
	printf("Enter the size : \n");
	scanf("%d", &arg.size);

	int i;
	for(i = 0; i < arg.size; i++)
		scanf("%d", &arg.arr[i]);

	arraysum_1_arg = arg;

	result_1 = arraysum_1(&arraysum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("Sum is : %d\n", *result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	arraysum_calc_1 (host);
exit (0);
}
