/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARRAYSUM_H_RPCGEN
#define _ARRAYSUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	int size;
	int arr[128];
};
typedef struct args args;

#define ARRAYSUM_CALC 0x1fffffff
#define ARRAYSUM_CALC_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ARRAYSUM 1
extern  int * arraysum_1(args *, CLIENT *);
extern  int * arraysum_1_svc(args *, struct svc_req *);
extern int arraysum_calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ARRAYSUM 1
extern  int * arraysum_1();
extern  int * arraysum_1_svc();
extern int arraysum_calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARRAYSUM_H_RPCGEN */
