/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <stdio.h>
#include <dirent.h>
#include <sys/types.h>
#define M 128

char curdir[M] = {'\0'}; 
char fname[M];

char* get_fullname(char* f)
{
	if(curdir[0] == '\0')
		strcpy(curdir, "/home/utkarsh/RPC/NFSystem");

	strcpy(fname, curdir);
	strcat(fname, "/");
	strcat(fname, f);
}

buf *
nfs_ls_1_svc(void *argp, struct svc_req *rqstp)
{
	static buf result;
	memset(result.buffer, 0, sizeof(result.buffer));

	if(curdir[0] == '\0')
	{
//	    getcwd(curdir, M);
		strcpy(curdir, "/home/utkarsh/RPC/NFSystem");
	}

	DIR* directory;
	struct dirent* dir_store;
	directory = opendir(curdir);
	
	while((dir_store = readdir(directory)) != NULL)
	{
		if (dir_store->d_name[0] != '.')				//	Ignoring . and .. directory	
		{
			strcat(result.buffer, dir_store->d_name);
			strcat(result.buffer, "\n");
		}
	}

	return &result;
}

int *
nfs_create_1_svc(file_args *argp, struct svc_req *rqstp)
{
	static int  result;

	FILE* fptr = fopen(get_fullname(argp->filename), "r+");
    if (fptr == NULL)
    {
		result = 0;
        return &result;
    }
	
	fclose(fptr);
	result = 1;
	return &result;
}

int *
nfs_rm_1_svc(file_args *argp, struct svc_req *rqstp)
{
	static int  result;
	unlink(get_fullname(argp->filename));
	result = 1;
	return &result;
}

buf *
nfs_cd_1_svc(file_args *argp, struct svc_req *rqstp)
{ 
	static buf result;
	char* tmp = argp->filename;

	if(curdir[0] == '\0')
		strcpy(curdir, "/home/utkarsh/RPC/NFSystem");

	if (argp->filename == NULL)
		return NULL;

	if (strncmp(argp->filename, "..", 2) == 0)
	{
		int i = strlen(curdir);
		for (; i >= 0; i--)
			if (curdir[i] == '/')
				break;
		curdir[i] = '\0'; 
		tmp = tmp + 2;		
	}

	if (tmp[0] != '/')
		strcat(curdir, "/");
	strcat(curdir, tmp);
	
	if (curdir[strlen(curdir) - 1] == '/')
		curdir[strlen(curdir) - 1] = '\0';

	strcpy(result.buffer, curdir);
	return &result;
}

buf *
read_1_svc(file_args *argp, struct svc_req *rqstp)
{
	static buf result;

	FILE* fptr = fopen(get_fullname(argp->filename), "r");
	fseek(fptr, argp->offset, SEEK_SET);
	fread(result.buffer, sizeof(char), argp->size, fptr);
	fclose(fptr);

	return &result;
}

int *
write_1_svc(file_write *argp, struct svc_req *rqstp)
{
	static int  result;

	FILE* fptr = fopen(get_fullname(argp->file_data.filename), "r+");
	
	fseek(fptr, argp->file_data.offset, SEEK_SET);
	fprintf(fptr, "%s", argp->data.buffer);
	fclose(fptr);

	result = 1;
	return &result;
}

int *
mkdir_1_svc(file_args *argp, struct svc_req *rqstp)
{
	static int  result;
//	result = mkdir(get_fullname(argp->filename), 0777);	
	return &result;
}

int *
rmdir_1_svc(file_args *argp, struct svc_req *rqstp)
{
	static int  result;
//	result = rmdir(get_fullname(argp->filename));
	return &result;
}
