/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LINKLIST_H_RPCGEN
#define _LINKLIST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct node {
	int data;
	struct node *next;
};
typedef struct node node;

struct nodeptr {
	struct node *ptr;
};
typedef struct nodeptr nodeptr;

#define LINKLIST 0x1fffffff
#define LINKLIST_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define addNode 1
extern  void * addnode_1(int *, CLIENT *);
extern  void * addnode_1_svc(int *, struct svc_req *);
#define print 2
extern  struct nodeptr * print_1(void *, CLIENT *);
extern  struct nodeptr * print_1_svc(void *, struct svc_req *);
#define addone 3
extern  void * addone_1(void *, CLIENT *);
extern  void * addone_1_svc(void *, struct svc_req *);
extern int linklist_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addNode 1
extern  void * addnode_1();
extern  void * addnode_1_svc();
#define print 2
extern  struct nodeptr * print_1();
extern  struct nodeptr * print_1_svc();
#define addone 3
extern  void * addone_1();
extern  void * addone_1_svc();
extern int linklist_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_nodeptr (XDR *, nodeptr*);

#else /* K&R C */
extern bool_t xdr_node ();
extern bool_t xdr_nodeptr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LINKLIST_H_RPCGEN */
