/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linklist.h"

node* head = NULL;

void *
addnode_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	
	if (head == NULL)
	{
		head = (node *) malloc(sizeof(node));
		head->data = *argp;
		head->next = NULL;
	}
	else
	{
		node* temp = head;
		while (temp->next != NULL)
			temp = temp->next;

		temp->next = (node *) malloc(sizeof(node));
		temp = temp->next;
		temp->data = *argp;
		temp->next = NULL;
	}

	return (void *) &result;
}

struct nodeptr *
print_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct nodeptr  result;
	result.ptr = head;
	return &result;
}

void *
addone_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
