/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct buf {
	u_int size;
	char buffer[1024];
};
typedef struct buf buf;

struct file_args {
	char filename[128];
	int offset;
	u_int size;
};
typedef struct file_args file_args;

struct file_write {
	struct buf data;
	struct file_args file_data;
};
typedef struct file_write file_write;

#define nfs_rpc 0x2fffffff
#define nfs 1

#if defined(__STDC__) || defined(__cplusplus)
#define nfs_ls 1
extern  buf * nfs_ls_1(void *, CLIENT *);
extern  buf * nfs_ls_1_svc(void *, struct svc_req *);
#define nfs_create 2
extern  int * nfs_create_1(file_args *, CLIENT *);
extern  int * nfs_create_1_svc(file_args *, struct svc_req *);
#define nfs_rm 3
extern  int * nfs_rm_1(file_args *, CLIENT *);
extern  int * nfs_rm_1_svc(file_args *, struct svc_req *);
#define nfs_cd 4
extern  buf * nfs_cd_1(file_args *, CLIENT *);
extern  buf * nfs_cd_1_svc(file_args *, struct svc_req *);
#define read 5
extern  buf * read_1(file_args *, CLIENT *);
extern  buf * read_1_svc(file_args *, struct svc_req *);
#define write 6
extern  int * write_1(file_write *, CLIENT *);
extern  int * write_1_svc(file_write *, struct svc_req *);
#define mkdir 7
extern  int * mkdir_1(file_args *, CLIENT *);
extern  int * mkdir_1_svc(file_args *, struct svc_req *);
#define rmdir 8
extern  int * rmdir_1(file_args *, CLIENT *);
extern  int * rmdir_1_svc(file_args *, struct svc_req *);
extern int nfs_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nfs_ls 1
extern  buf * nfs_ls_1();
extern  buf * nfs_ls_1_svc();
#define nfs_create 2
extern  int * nfs_create_1();
extern  int * nfs_create_1_svc();
#define nfs_rm 3
extern  int * nfs_rm_1();
extern  int * nfs_rm_1_svc();
#define nfs_cd 4
extern  buf * nfs_cd_1();
extern  buf * nfs_cd_1_svc();
#define read 5
extern  buf * read_1();
extern  buf * read_1_svc();
#define write 6
extern  int * write_1();
extern  int * write_1_svc();
#define mkdir 7
extern  int * mkdir_1();
extern  int * mkdir_1_svc();
#define rmdir 8
extern  int * rmdir_1();
extern  int * rmdir_1_svc();
extern int nfs_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_buf (XDR *, buf*);
extern  bool_t xdr_file_args (XDR *, file_args*);
extern  bool_t xdr_file_write (XDR *, file_write*);

#else /* K&R C */
extern bool_t xdr_buf ();
extern bool_t xdr_file_args ();
extern bool_t xdr_file_write ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
