/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#define M 128

void
nfs_rpc_1(char *host)
{
	CLIENT *clnt;
	buf  *result_1;
	char *nfs_ls_1_arg;
	int  *result_2;
	file_args  nfs_create_1_arg;
	int  *result_3;
	file_args  nfs_rm_1_arg;
	buf  *result_4;
	file_args  nfs_cd_1_arg;
	buf  *result_5;
	file_args  read_1_arg;
	int  *result_6;
	file_write  write_1_arg;
	int  *result_7;
	file_args  mkdir_1_arg;
	int  *result_8;
	file_args  rmdir_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, nfs_rpc, nfs, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Available commands : ls, rm, cd, create, read, write, mkdir, rmdir\n\n");

    char input[M], cmd[M], fname[M];
    char home[] = "utkarsh@nfs:~$ ";
    int offset, size;
    char cmdline[M];
    strcpy(cmdline, home);

    while (1)
    {
        printf("%s", cmdline);
        fgets(input, M, stdin);
        
        char * token = strtok(input, " ");
        strcpy(cmd, token);

        token = strtok(NULL, " ");

		memset(fname, 0, sizeof(fname));        
		if (token != NULL)
        {
            strcpy(fname, token);
			if (fname[strlen(fname) - 1] == '\n')
				fname[strlen(fname) - 1] = '\0';

            token = strtok(NULL, " ");

            size = 0;
            if (token != NULL)
            {
                size = atoi(token);
                offset = 0;
                token = strtok(NULL, " ");
                if (token != NULL)
                {
                    offset = atoi(token);
                }
            }
        }

        if (strncmp("ls", cmd, 2) == 0)
        {
            result_1 = nfs_ls_1((void*)&nfs_ls_1_arg, clnt);
            if (result_1 == (buf *) NULL) {
                clnt_perror (clnt, "call failed");
            }

            printf("%s", result_1->buffer); 
        }
        else if (strncmp("create", cmd, 6) == 0)
        {
            strcpy(nfs_create_1_arg.filename, fname);
            nfs_create_1_arg.offset = offset;

            result_2 = nfs_create_1(&nfs_create_1_arg, clnt);
            if (result_2 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
            }

            if (*result_2 > 0)
                printf("File %s created\n", fname);
            else
                printf("File %s not created\n", fname);
        }
		else if (strncmp("rmdir", cmd, 5) == 0)
        {
            strcpy(rmdir_1_arg.filename, fname);

            result_8 = rmdir_1(&rmdir_1_arg, clnt);
            if (result_8 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
            }

            if (*result_8 > 0)
                printf("directory %s removed\n", fname);
            else
                printf("directory removal unsuccessfull\n");
        }
        else if (strncmp("rm", cmd, 2) == 0)
        {
            strcpy(nfs_rm_1_arg.filename, fname);

            result_3 = nfs_rm_1(&nfs_rm_1_arg, clnt);
            if (result_3 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
            }

            if (*result_3 == 1)
                printf("File %s removed\n", fname);
            else
                printf("File %s not removed\n", fname);
        }
        else if (strncmp("cd", cmd, 2) == 0)
        {
            strcpy(nfs_cd_1_arg.filename, fname);

            result_4 = nfs_cd_1(&nfs_cd_1_arg, clnt);
            if (result_4 == (buf *) NULL) {
                clnt_perror (clnt, "call failed");
            }
			
			strcpy(cmdline, result_4->buffer);
			strcat(cmdline, " $ ");
        }
        else if (strncmp("read", cmd, 4) == 0)
        {
            strcpy(read_1_arg.filename, fname);
            read_1_arg.offset = offset;
            
			int chunk = 1024;
			int i = 0;
			read_1_arg.size = chunk;

			for (; i < size / chunk; i++)
			{
				result_5 = read_1(&read_1_arg, clnt);
				printf("%s", result_5->buffer);
				read_1_arg.offset += chunk;
			}

			read_1_arg.size = size - i*chunk;
			result_5 = read_1(&read_1_arg, clnt);
			printf("%s", result_5->buffer);
        }
        else if (strncmp("write", cmd, 5) == 0)
        {
			printf("Enter the text to write :\n");				
			fgets(write_1_arg.data.buffer, 1024, stdin);

			strcpy(write_1_arg.file_data.filename, fname);
            write_1_arg.file_data.offset = offset;
            write_1_arg.file_data.size = size;

            result_6 = write_1(&write_1_arg, clnt);
            if (result_6 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
            }

            if (*result_6 == 1)
                printf("Written into %s file\n", fname);
            else
                printf("Write unsuccessfull\n");
        }
        else if (strncmp("mkdir", cmd, 5) == 0)
        {
            strcpy(mkdir_1_arg.filename, fname);

            result_7 = mkdir_1(&mkdir_1_arg, clnt);
            if (result_7 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
            }

            if (*result_7 > 0)
                printf("Made directory %s\n", fname);
            else
                printf("directory creation unsuccessfull\n");
        }
        else if (strncmp("exit", cmd, 4) == 0)
        {
            exit(1);
        }
        else
        {
            printf("Command not found\n");
        }
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfs_rpc_1 (host);
exit (0);
}
