/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
For compile and run :

COMPILE:
	make -f Makefile.add

RUN: (open each command in a new terminal)
	sudo ./square_server
	square_client localhost

*/

#include "square.h"
#define sq(x) ((x)*(x))

int *
square_1_svc(args *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */
	printf("Entered number is : %d\n", argp->num);
	result = sq(argp->num);	

	return &result;
}
